---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-polya-diff"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "Workspaces"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-polya-diff"

## Pipeline-specific parameters:

# Control tail estimates
control_tails:
    wt_1: "wt-1/tails/filtered_tails.tsv"
    wt_2: "wt-2/tails/filtered_tails.tsv"

# Treated tail estimates
treated_tails:
    mut_1: "mut1/tails/filtered_tails.tsv"
    mut_2: "mut2/tails/filtered_tails.tsv"

# Minimum reads per transcript
min_reads_per_transcript: 10

# Generate per-transcript plots
per_transcript_plots: "true"

# Threads
threads: 50

